In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [2]:
df = sns.load_dataset('iris')

In [3]:
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [6]:
df['species'].unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [9]:
df.isna().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

In [11]:
X = df.drop('species', axis=1)
y = df['species']

In [12]:
from sklearn.model_selection import train_test_split

In [13]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [15]:
from sklearn.neighbors import KNeighborsClassifier

In [24]:
model_knn = KNeighborsClassifier(n_neighbors=3)
model_knn.fit(X,y)

KNeighborsClassifier(n_neighbors=3)

In [25]:
model_knn.score(X_test,y_test)

0.98

In [26]:
from sklearn.svm import SVC

In [49]:
model_svm = SVC(gamma='auto')

In [50]:
model_svm.fit(X_test,y_test)

SVC(gamma='auto')

In [51]:
model_svm.score(X_test,y_test)

0.98

### Using Grid Search CV

In [61]:
from sklearn.model_selection import GridSearchCV

In [62]:
classifier_svm = GridSearchCV((model_svm),{
    'C' : [1,10,20,30],
    'kernel' : ['linear', 'rbf']
},cv=5, return_train_score=False)

In [63]:
classifier_svm.fit(X,y)

GridSearchCV(cv=5, estimator=SVC(gamma='auto'),
             param_grid={'C': [1, 10, 20, 30], 'kernel': ['linear', 'rbf']})

In [64]:
classifier_svm.cv_results_

{'mean_fit_time': array([0.00248523, 0.00256386, 0.00211024, 0.00207477, 0.00209589,
        0.00220575, 0.00199132, 0.00210233]),
 'std_fit_time': array([4.38974703e-04, 4.91425969e-04, 6.56203124e-05, 2.79372864e-05,
        9.19393977e-05, 1.30097274e-04, 4.12279154e-05, 7.17554214e-05]),
 'mean_score_time': array([0.00174007, 0.00223112, 0.00186181, 0.0017931 , 0.00150537,
        0.00183196, 0.00147176, 0.00181475]),
 'std_score_time': array([1.91331205e-04, 3.18642306e-04, 3.72735039e-04, 4.61376359e-05,
        5.81493090e-05, 1.24599602e-04, 2.08214646e-05, 8.00782100e-05]),
 'param_C': masked_array(data=[1, 1, 10, 10, 20, 20, 30, 30],
              mask=[False, False, False, False, False, False, False, False],
        fill_value=999999),
 'param_kernel': masked_array(data=['linear', 'rbf', 'linear', 'rbf', 'linear', 'rbf',
                    'linear', 'rbf'],
              mask=[False, False, False, False, False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'params': [{'C': 1, 'kernel': 'linear'},
  {'C': 1, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'rbf'},
  {'C': 20, 'kernel': 'linear'},
  {'C': 20, 'kernel': 'rbf'},
  {'C': 30, 'kernel': 'linear'},
  {'C': 30, 'kernel': 'rbf'}],
 'split0_test_score': array([0.96666667, 0.96666667, 1.        , 0.96666667, 1.        ,
        0.96666667, 1.        , 0.96666667]),
 'split1_test_score': array([1., 1., 1., 1., 1., 1., 1., 1.]),
 'split2_test_score': array([0.96666667, 0.96666667, 0.9       , 0.96666667, 0.9       ,
        0.9       , 0.9       , 0.9       ]),
 'split3_test_score': array([0.96666667, 0.96666667, 0.96666667, 0.96666667, 0.93333333,
        0.96666667, 0.9       , 0.93333333]),
 'split4_test_score': array([1., 1., 1., 1., 1., 1., 1., 1.]),
 'mean_test_score': array([0.98      , 0.98      , 0.97333333, 0.98      , 0.96666667,
        0.96666667, 0.96      , 0.96      ]),
 'std_test_score': array([0.01632993, 0.01632993, 0.03887301, 0.01632993, 0.0421637 ,
        0.03651484, 0.04898979, 0.03887301]),
 'rank_test_score': array([1, 1, 4, 1, 6, 5, 7, 7], dtype=int32)}

In [71]:
results_svm = pd.DataFrame(classifier_svm.cv_results_)

In [72]:
results_svm

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.002485,0.000439,0.001740,0.000191,1,linear,"{'C': 1, 'kernel': 'linear'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
1,0.002564,0.000491,0.002231,0.000319,1,rbf,"{'C': 1, 'kernel': 'rbf'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
2,0.002110,0.000066,0.001862,0.000373,10,linear,"{'C': 10, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.966667,1.0,0.973333,0.038873,4
3,0.002075,0.000028,0.001793,0.000046,10,rbf,"{'C': 10, 'kernel': 'rbf'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
4,0.002096,0.000092,0.001505,0.000058,20,linear,"{'C': 20, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.933333,1.0,0.966667,0.042164,6
5,0.002206,0.000130,0.001832,0.000125,20,rbf,"{'C': 20, 'kernel': 'rbf'}",0.966667,1.0,0.900000,0.966667,1.0,0.966667,0.036515,5
6,0.001991,0.000041,0.001472,0.000021,30,linear,"{'C': 30, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.900000,1.0,0.960000,0.048990,7
7,0.002102,0.000072,0.001815,0.000080,30,rbf,"{'C': 30, 'kernel': 'rbf'}",0.966667,1.0,0.900000,0.933333,1.0,0.960000,0.038873,7

In [74]:
results_svm[['param_C','param_kernel','mean_test_score']]

   param_C param_kernel  mean_test_score
0        1       linear         0.980000
1        1          rbf         0.980000
2       10       linear         0.973333
3       10          rbf         0.980000
4       20       linear         0.966667
5       20          rbf         0.966667
6       30       linear         0.960000
7       30          rbf         0.960000

In [68]:
classifier_knn = GridSearchCV((model_knn),{
    'n_neighbors' : [5,11,15,21],
    'algorithm' : ['auto', 'brute', 'kd_tree']
},cv=5, return_train_score=False)

In [69]:
classifier_knn.fit(X,y)

GridSearchCV(cv=5, estimator=KNeighborsClassifier(n_neighbors=3),
             param_grid={'algorithm': ['auto', 'brute', 'kd_tree'],
                         'n_neighbors': [5, 11, 15, 21]})

In [75]:
results_knn = pd.DataFrame(classifier_knn.cv_results_)

In [76]:
results_knn

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_algorithm,param_n_neighbors,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.001507,0.000370,0.002178,0.000674,auto,5,"{'algorithm': 'auto', 'n_neighbors': 5}",0.966667,1.0,0.933333,0.966667,1.0,0.973333,0.024944,4
1,0.001193,0.000444,0.001828,0.000533,auto,11,"{'algorithm': 'auto', 'n_neighbors': 11}",0.933333,1.0,1.000000,0.966667,1.0,0.980000,0.026667,1
2,0.001448,0.000331,0.002101,0.000349,auto,15,"{'algorithm': 'auto', 'n_neighbors': 15}",0.933333,1.0,0.933333,0.966667,1.0,0.966667,0.029814,7
3,0.001206,0.000139,0.001681,0.000141,auto,21,"{'algorithm': 'auto', 'n_neighbors': 21}",0.933333,1.0,0.933333,0.966667,1.0,0.966667,0.029814,7
4,0.000967,0.000088,0.560713,1.112214,brute,5,"{'algorithm': 'brute', 'n_neighbors': 5}",0.966667,1.0,0.933333,0.966667,1.0,0.973333,0.024944,4
5,0.000893,0.000033,0.004476,0.000347,brute,11,"{'algorithm': 'brute', 'n_neighbors': 11}",0.933333,1.0,1.000000,0.966667,1.0,0.980000,0.026667,1
6,0.000899,0.000026,0.005409,0.000436,brute,15,"{'algorithm': 'brute', 'n_neighbors': 15}",0.933333,1.0,0.933333,0.966667,1.0,0.966667,0.029814,7
7,0.000878,0.000014,0.005067,0.000195,brute,21,"{'algorithm': 'brute', 'n_neighbors': 21}",0.933333,1.0,0.933333,0.966667,1.0,0.966667,0.029814,7
8,0.000918,0.000040,0.001353,0.000083,kd_tree,5,"{'algorithm': 'kd_tree', 'n_neighbors': 5}",0.966667,1.0,0.933333,0.966667,1.0,0.973333,0.024944,4
9,0.001207,0.000648,0.001368,0.000057,kd_tree,11,"{'algorithm': 'kd_tree', 'n_neighbors': 11}",0.933333,1.0,1.000000,0.966667,1.0,0.980000,0.026667,1
10,0.000917,0.000112,0.001443,0.000101,kd_tree,15,"{'algorithm': 'kd_tree', 'n_neighbors': 15}",0.933333,1.0,0.933333,0.966667,1.0,0.966667,0.029814,7
11,0.000950,0.000131,0.001457,0.000157,kd_tree,21,"{'algorithm': 'kd_tree', 'n_neighbors': 21}",0.933333,1.0,0.933333,0.966667,1.0,0.966667,0.029814,7

In [77]:
results_knn[['param_algorithm','param_n_neighbors','mean_test_score']]

   param_algorithm  param_n_neighbors  mean_test_score
0             auto                  5         0.973333
1             auto                 11         0.980000
2             auto                 15         0.966667
3             auto                 21         0.966667
4            brute                  5         0.973333
5            brute                 11         0.980000
6            brute                 15         0.966667
7            brute                 21         0.966667
8          kd_tree                  5         0.973333
9          kd_tree                 11         0.980000
10         kd_tree                 15         0.966667
11         kd_tree                 21         0.966667