In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [2]:
df = sns.load_dataset('titanic')

In [3]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [4]:
df.columns

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone'],
      dtype='object')

In [5]:
df.describe()

         survived      pclass         age       sibsp       parch        fare
count  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object
 8   class        891 non-null    category
 9   who          891 non-null    object
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object
 13  alive        891 non-null    object
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB

In [7]:
df.drop(['class', 'who', 'adult_male', 'deck', 'embark_town','alive'], axis=1, inplace=True)
df.head()

   survived  pclass     sex   age  sibsp  parch     fare embarked  alone
0         0       3    male  22.0      1      0   7.2500        S  False
1         1       1  female  38.0      1      0  71.2833        C  False
2         1       3  female  26.0      0      0   7.9250        S   True
3         1       1  female  35.0      1      0  53.1000        S  False
4         0       3    male  35.0      0      0   8.0500        S   True

In [8]:
df.isnull().sum()

survived      0
pclass        0
sex           0
age         177
sibsp         0
parch         0
fare          0
embarked      2
alone         0
dtype: int64

In [9]:
df['age'].fillna(df['age'].mean(), inplace=True)

In [10]:
df.dropna(subset=['embarked'], inplace=True)

In [11]:
df.isnull().sum()

survived    0
pclass      0
sex         0
age         0
sibsp       0
parch       0
fare        0
embarked    0
alone       0
dtype: int64

## Logistic Regression

In [12]:
from sklearn.preprocessing import LabelEncoder
enc = LabelEncoder()

In [13]:
df['sex'] = enc.fit_transform(df['sex'])
df['embarked'] = enc.fit_transform(df['embarked'])
df = df.astype(int)

In [14]:
df.head()

   survived  pclass  sex  age  sibsp  parch  fare  embarked  alone
0         0       3    1   22      1      0     7         2      0
1         1       1    0   38      1      0    71         0      0
2         1       3    0   26      0      0     7         2      1
3         1       1    0   35      1      0    53         2      0
4         0       3    1   35      0      0     8         2      1

In [15]:
X = df.drop('survived', axis=1)
y = df['survived']

In [16]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [17]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()

model.fit(X_train, y_train)

LogisticRegression()

In [18]:
y_pred = model.predict(X_test)

In [19]:
y_pred

array([0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0,
       0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1,
       0, 1, 0, 0, 0, 1, 1, 0])

In [20]:
y_test

281    0
435    1
39     1
418    0
585    1
      ..
711    0
840    0
381    1
141    1
174    0
Name: survived, Length: 294, dtype: int64

In [21]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [22]:
accuracy_score(y_pred,y_test)

0.8163265306122449

In [23]:
confusion_matrix(y_test, y_pred)

array([[157,  27],
       [ 27,  83]])

In [24]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.85      0.85      0.85       184
           1       0.75      0.75      0.75       110

    accuracy                           0.82       294
   macro avg       0.80      0.80      0.80       294
weighted avg       0.82      0.82      0.82       294

In [25]:
df

     survived  pclass  sex  age  sibsp  parch  fare  embarked  alone
0           0       3    1   22      1      0     7         2      0
1           1       1    0   38      1      0    71         0      0
2           1       3    0   26      0      0     7         2      1
3           1       1    0   35      1      0    53         2      0
4           0       3    1   35      0      0     8         2      1
..        ...     ...  ...  ...    ...    ...   ...       ...    ...
886         0       2    1   27      0      0    13         2      1
887         1       1    0   19      0      0    30         2      1
888         0       3    0   29      1      2    23         2      0
889         1       1    1   26      0      0    30         0      1
890         0       3    1   32      0      0     7         1      1

[889 rows x 9 columns]

In [26]:
X_train

     pclass  sex  age  sibsp  parch  fare  embarked  alone
6         1    1   54      0      0    51         2      1
576       2    0   34      0      0    13         2      1
445       1    1    4      0      2    81         2      0
74        3    1   32      0      0    56         2      1
670       2    0   40      1      1    39         2      0
..      ...  ...  ...    ...    ...   ...       ...    ...
107       3    1   29      0      0     7         2      1
271       3    1   25      0      0     0         2      1
862       1    0   48      0      0    25         2      1
436       3    0   21      2      2    34         2      0
103       3    1   33      0      0     8         2      1

[595 rows x 8 columns]

In [27]:
X_test

     pclass  sex  age  sibsp  parch  fare  embarked  alone
281       3    1   28      0      0     7         2      1
435       1    0   14      1      2   120         2      0
39        3    0   14      1      0    11         0      0
418       2    1   30      0      0    13         2      1
585       1    0   18      0      2    79         2      0
..      ...  ...  ...    ...    ...   ...       ...    ...
711       1    1   29      0      0    26         2      1
840       3    1   20      0      0     7         2      1
381       3    0    1      0      2    15         0      0
141       3    0   22      0      0     7         2      1
174       1    1   56      0      0    30         0      1

[294 rows x 8 columns]

## KNN

In [28]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [30]:
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.fit_transform(X_test)

In [31]:
from sklearn.neighbors import KNeighborsClassifier

In [45]:
knn_model = KNeighborsClassifier(n_neighbors = 5)
knn_model.fit(X_train_scaled,y_train)

KNeighborsClassifier()

In [46]:
y_pred_knn = knn_model.predict(X_test_scaled)

In [47]:
accuracy_score(y_test,y_pred_knn)

0.8061224489795918

In [48]:
confusion_matrix(y_test,y_pred_knn)

array([[158,  26],
       [ 31,  79]])

In [49]:
print(classification_report(y_test,y_pred_knn))

              precision    recall  f1-score   support

           0       0.84      0.86      0.85       184
           1       0.75      0.72      0.73       110

    accuracy                           0.81       294
   macro avg       0.79      0.79      0.79       294
weighted avg       0.80      0.81      0.81       294

## Naive Bayes

In [50]:
from sklearn.naive_bayes import GaussianNB
model_nb = GaussianNB()

In [60]:
X_train

     pclass  sex  age  sibsp  parch  fare  embarked  alone
6         1    1   54      0      0    51         2      1
576       2    0   34      0      0    13         2      1
445       1    1    4      0      2    81         2      0
74        3    1   32      0      0    56         2      1
670       2    0   40      1      1    39         2      0
..      ...  ...  ...    ...    ...   ...       ...    ...
107       3    1   29      0      0     7         2      1
271       3    1   25      0      0     0         2      1
862       1    0   48      0      0    25         2      1
436       3    0   21      2      2    34         2      0
103       3    1   33      0      0     8         2      1

[595 rows x 8 columns]

In [61]:
y_train

6      0
576    1
445    1
74     1
670    1
      ..
107    1
271    1
862    1
436    0
103    0
Name: survived, Length: 595, dtype: int64

In [51]:
model_nb.fit(X_train,y_train)

GaussianNB()

In [54]:
y_pred_nb = model_nb.predict(X_test)
y_pred_nb

array([0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0,
       0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1,
       0, 1, 1, 0, 0, 1, 1, 1])

In [62]:
model_nb.predict_proba(X_test)

array([[9.67812580e-01, 3.21874205e-02],
       [9.25803593e-04, 9.99074196e-01],
       [4.46639030e-02, 9.55336097e-01],
       [9.33106592e-01, 6.68934080e-02],
       [9.22667118e-03, 9.90773329e-01],
       [9.67307219e-01, 3.26927805e-02],
       [9.29380255e-01, 7.06197455e-02],
       [9.64316165e-01, 3.56838350e-02],
       [3.40066732e-04, 9.99659933e-01],
       [1.08411786e-03, 9.98915882e-01],
       [9.11608405e-01, 8.83915950e-02],
       [2.50060761e-01, 7.49939239e-01],
       [9.64062133e-01, 3.59378666e-02],
       [7.09769878e-01, 2.90230122e-01],
       [9.68344922e-01, 3.16550784e-02],
       [9.67465669e-01, 3.25343314e-02],
       [1.77125408e-02, 9.82287459e-01],
       [8.43444258e-01, 1.56555742e-01],
       [4.50170776e-01, 5.49829224e-01],
       [9.68130620e-01, 3.18693804e-02],
       [9.99999770e-01, 2.30190113e-07],
       [1.96553830e-02, 9.80344617e-01],
       [9.16533083e-01, 8.34669166e-02],
       [3.97385171e-01, 6.02614829e-01],
       [9.68247933e-01, 3.17520665e-02],
       [4.02551722e-01, 5.97448278e-01],
       [7.16956274e-01, 2.83043726e-01],
       [1.76530544e-01, 8.23469456e-01],
       [7.51623648e-01, 2.48376352e-01],
       [9.30084385e-01, 6.99156149e-02],
       [7.70536848e-01, 2.29463152e-01],
       [3.20321550e-01, 6.79678450e-01],
       [9.68247933e-01, 3.17520665e-02],
       [3.65082884e-01, 6.34917116e-01],
       [9.88994787e-01, 1.10052130e-02],
       [5.31879263e-01, 4.68120737e-01],
       [1.38826880e-01, 8.61173120e-01],
       [6.07521421e-36, 1.00000000e+00],
       [8.43946570e-01, 1.56053430e-01],
       [9.68247933e-01, 3.17520665e-02],
       [9.26723997e-01, 7.32760028e-02],
       [2.50719767e-01, 7.49280233e-01],
       [9.27185516e-01, 7.28144835e-02],
       [9.67035208e-01, 3.29647917e-02],
       [7.94512112e-01, 2.05487888e-01],
       [3.92818819e-01, 6.07181181e-01],
       [1.10732878e-01, 8.89267122e-01],
       [9.66058718e-01, 3.39412817e-02],
       [9.34446221e-01, 6.55537788e-02],
       [1.12116971e-10, 1.00000000e+00],
       [8.07449195e-02, 9.19255081e-01],
       [2.85540696e-01, 7.14459304e-01],
       [9.64867225e-01, 3.51327753e-02],
       [8.57497003e-01, 1.42502997e-01],
       [8.06169796e-02, 9.19383020e-01],
       [2.17314356e-01, 7.82685644e-01],
       [4.53463223e-02, 9.54653678e-01],
       [9.68937844e-01, 3.10621562e-02],
       [9.60052000e-01, 3.99480001e-02],
       [9.32879580e-01, 6.71204198e-02],
       [9.99873926e-01, 1.26074249e-04],
       [2.30306432e-01, 7.69693568e-01],
       [1.63018234e-03, 9.98369818e-01],
       [9.60052000e-01, 3.99480001e-02],
       [2.51572769e-01, 7.48427231e-01],
       [9.19650115e-01, 8.03498852e-02],
       [9.64884083e-01, 3.51159171e-02],
       [9.44070305e-01, 5.59296949e-02],
       [1.46017371e-03, 9.98539826e-01],
       [5.95324783e-03, 9.94046752e-01],
       [9.31159815e-01, 6.88401853e-02],
       [4.98143054e-05, 9.99950186e-01],
       [5.92270459e-02, 9.40772954e-01],
       [9.67567671e-01, 3.24323293e-02],
       [2.68250729e-01, 7.31749271e-01],
       [2.59010996e-01, 7.40989004e-01],
       [9.62769417e-01, 3.72305834e-02],
       [9.69118142e-01, 3.08818578e-02],
       [1.13094843e-01, 8.86905157e-01],
       [7.83090141e-01, 2.16909859e-01],
       [4.25175669e-01, 5.74824331e-01],
       [1.56827699e-02, 9.84317230e-01],
       [1.16697309e-01, 8.83302691e-01],
       [3.20321550e-01, 6.79678450e-01],
       [8.66489795e-01, 1.33510205e-01],
       [9.49739071e-01, 5.02609293e-02],
       [9.68359856e-01, 3.16401442e-02],
       [9.27185516e-01, 7.28144835e-02],
       [9.66572762e-01, 3.34272380e-02],
       [9.68247933e-01, 3.17520665e-02],
       [9.68631734e-01, 3.13682657e-02],
       [4.08195702e-01, 5.91804298e-01],
       [9.64867225e-01, 3.51327753e-02],
       [9.68959195e-01, 3.10408053e-02],
       [9.44609513e-01, 5.53904867e-02],
       [4.47357369e-02, 9.55264263e-01],
       [9.68130620e-01, 3.18693804e-02],
       [9.34343597e-01, 6.56564033e-02],
       [8.60771123e-01, 1.39228877e-01],
       [9.49739071e-01, 5.02609293e-02],
       [9.66572762e-01, 3.34272380e-02],
       [8.30418650e-08, 9.99999917e-01],
       [9.74770890e-01, 2.52291100e-02],
       [9.68931656e-01, 3.10683444e-02],
       [8.98917769e-01, 1.01082231e-01],
       [9.68196988e-01, 3.18030119e-02],
       [4.25696056e-01, 5.74303944e-01],
       [2.18557498e-02, 9.78144250e-01],
       [8.29659556e-01, 1.70340444e-01],
       [9.64316165e-01, 3.56838350e-02],
       [9.63685699e-01, 3.63143008e-02],
       [9.38564037e-02, 9.06143596e-01],
       [9.99994889e-01, 5.11075393e-06],
       [2.82528511e-02, 9.71747149e-01],
       [8.97619528e-01, 1.02380472e-01],
       [9.08293039e-01, 9.17069608e-02],
       [9.19328334e-01, 8.06716664e-02],
       [9.28811918e-01, 7.11880816e-02],
       [4.36320492e-01, 5.63679508e-01],
       [9.84478080e-01, 1.55219200e-02],
       [7.16367997e-01, 2.83632003e-01],
       [1.25081482e-02, 9.87491852e-01],
       [9.65965522e-01, 3.40344781e-02],
       [9.68529909e-01, 3.14700908e-02],
       [9.69379991e-04, 9.99030620e-01],
       [1.26242051e-03, 9.98737579e-01],
       [3.97385171e-01, 6.02614829e-01],
       [2.60299011e-02, 9.73970099e-01],
       [2.94608954e-01, 7.05391046e-01],
       [7.21830944e-01, 2.78169056e-01],
       [2.55718719e-01, 7.44281281e-01],
       [9.15415876e-01, 8.45841237e-02],
       [9.21653927e-01, 7.83460733e-02],
       [8.43444258e-01, 1.56555742e-01],
       [4.22514660e-01, 5.77485340e-01],
       [1.15885500e-01, 8.84114500e-01],
       [9.68631734e-01, 3.13682657e-02],
       [2.44190912e-01, 7.55809088e-01],
       [2.26965256e-01, 7.73034744e-01],
       [9.00837043e-02, 9.09916296e-01],
       [5.92270459e-02, 9.40772954e-01],
       [9.68130620e-01, 3.18693804e-02],
       [2.54459396e-01, 7.45540604e-01],
       [8.51516662e-01, 1.48483338e-01],
       [8.40471833e-04, 9.99159528e-01],
       [4.97303460e-01, 5.02696540e-01],
       [8.83892920e-01, 1.16107080e-01],
       [2.67294784e-05, 9.99973271e-01],
       [9.68130620e-01, 3.18693804e-02],
       [1.01649766e-04, 9.99898350e-01],
       [9.66058718e-01, 3.39412817e-02],
       [1.30708740e-01, 8.69291260e-01],
       [6.97796595e-01, 3.02203405e-01],
       [7.14531601e-01, 2.85468399e-01],
       [6.31312401e-01, 3.68687599e-01],
       [2.41888692e-01, 7.58111308e-01],
       [7.30249743e-01, 2.69750257e-01],
       [1.96567540e-01, 8.03432460e-01],
       [8.67234814e-01, 1.32765186e-01],
       [4.31708623e-03, 9.95682914e-01],
       [9.30634471e-01, 6.93655287e-02],
       [3.56517151e-04, 9.99643483e-01],
       [9.68816787e-01, 3.11832135e-02],
       [9.49920583e-01, 5.00794166e-02],
       [6.45198195e-02, 9.35480181e-01],
       [2.31499155e-01, 7.68500845e-01],
       [2.80416635e-02, 9.71958336e-01],
       [9.64867225e-01, 3.51327753e-02],
       [9.69118142e-01, 3.08818578e-02],
       [1.09766077e-01, 8.90233923e-01],
       [2.44190912e-01, 7.55809088e-01],
       [1.21817438e-01, 8.78182562e-01],
       [3.24598355e-02, 9.67540164e-01],
       [9.60808001e-01, 3.91919994e-02],
       [3.85451186e-01, 6.14548814e-01],
       [9.08901559e-01, 9.10984413e-02],
       [9.83928225e-01, 1.60717753e-02],
       [1.33543010e-01, 8.66456990e-01],
       [1.89297968e-04, 9.99810702e-01],
       [5.94091170e-02, 9.40590883e-01],
       [9.68816787e-01, 3.11832135e-02],
       [1.00000000e+00, 3.80421924e-20],
       [9.99999994e-01, 6.08316961e-09],
       [9.99761863e-01, 2.38137325e-04],
       [9.64867225e-01, 3.51327753e-02],
       [9.67812580e-01, 3.21874205e-02],
       [9.68130620e-01, 3.18693804e-02],
       [7.72345630e-01, 2.27654370e-01],
       [9.28811918e-01, 7.11880816e-02],
       [8.62838131e-01, 1.37161869e-01],
       [9.80026918e-01, 1.99730824e-02],
       [8.98742716e-01, 1.01257284e-01],
       [3.20321550e-01, 6.79678450e-01],
       [9.22772216e-01, 7.72277840e-02],
       [9.20737677e-01, 7.92623230e-02],
       [7.07680705e-01, 2.92319295e-01],
       [9.64867225e-01, 3.51327753e-02],
       [8.80774016e-02, 9.11922598e-01],
       [5.18374159e-01, 4.81625841e-01],
       [9.79772363e-01, 2.02276366e-02],
       [9.99994328e-01, 5.67229933e-06],
       [4.34172248e-01, 5.65827752e-01],
       [7.65558148e-01, 2.34441852e-01],
       [9.68595778e-01, 3.14042217e-02],
       [9.60951182e-01, 3.90488176e-02],
       [5.13219148e-01, 4.86780852e-01],
       [9.67035208e-01, 3.29647917e-02],
       [8.45155877e-01, 1.54844123e-01],
       [3.37646063e-03, 9.96623539e-01],
       [4.07250984e-01, 5.92749016e-01],
       [9.68519655e-01, 3.14803455e-02],
       [4.87556302e-01, 5.12443698e-01],
       [9.49739071e-01, 5.02609293e-02],
       [3.61361484e-01, 6.38638516e-01],
       [9.98924559e-01, 1.07544120e-03],
       [9.08123611e-01, 9.18763890e-02],
       [2.70206448e-01, 7.29793552e-01],
       [9.30938991e-01, 6.90610086e-02],
       [9.68130620e-01, 3.18693804e-02],
       [2.51350568e-01, 7.48649432e-01],
       [9.68028950e-01, 3.19710505e-02],
       [2.54353032e-01, 7.45646968e-01],
       [2.73742237e-02, 9.72625776e-01],
       [4.06513408e-01, 5.93486592e-01],
       [2.36400173e-01, 7.63599827e-01],
       [9.28811918e-01, 7.11880816e-02],
       [7.89481343e-01, 2.10518657e-01],
       [4.60191215e-02, 9.53980879e-01],
       [4.22514660e-01, 5.77485340e-01],
       [1.78031173e-02, 9.82196883e-01],
       [3.20321550e-01, 6.79678450e-01],
       [9.49739071e-01, 5.02609293e-02],
       [9.64184862e-01, 3.58151382e-02],
       [1.00000000e+00, 9.48799408e-22],
       [9.48600495e-01, 5.13995053e-02],
       [9.49739071e-01, 5.02609293e-02],
       [9.99800411e-01, 1.99589107e-04],
       [2.63594935e-03, 9.97364051e-01],
       [9.29154837e-01, 7.08451629e-02],
       [9.99994585e-01, 5.41525778e-06],
       [1.32734713e-01, 8.67265287e-01],
       [8.43444258e-01, 1.56555742e-01],
       [6.55763125e-09, 9.99999993e-01],
       [9.31203967e-01, 6.87960326e-02],
       [3.21911150e-01, 6.78088850e-01],
       [9.41947726e-03, 9.90580523e-01],
       [3.20321550e-01, 6.79678450e-01],
       [9.33106592e-01, 6.68934080e-02],
       [7.57283770e-01, 2.42716230e-01],
       [9.65102680e-01, 3.48973200e-02],
       [9.33017949e-01, 6.69820510e-02],
       [9.68247933e-01, 3.17520665e-02],
       [8.29659556e-01, 1.70340444e-01],
       [1.57656279e-02, 9.84234372e-01],
       [9.62632643e-01, 3.73673575e-02],
       [2.27221235e-01, 7.72778765e-01],
       [8.21511303e-01, 1.78488697e-01],
       [2.62766298e-01, 7.37233702e-01],
       [9.29380255e-01, 7.06197455e-02],
       [9.28147599e-01, 7.18524005e-02],
       [8.61675915e-01, 1.38324085e-01],
       [9.69045328e-01, 3.09546718e-02],
       [9.68247933e-01, 3.17520665e-02],
       [3.95703584e-01, 6.04296416e-01],
       [8.36818738e-01, 1.63181262e-01],
       [3.27771574e-01, 6.72228426e-01],
       [7.87771298e-01, 2.12228702e-01],
       [6.95863967e-03, 9.93041360e-01],
       [4.16088341e-01, 5.83911659e-01],
       [9.64184862e-01, 3.58151382e-02],
       [8.72788661e-01, 1.27211339e-01],
       [5.17151129e-01, 4.82848871e-01],
       [2.57639136e-03, 9.97423609e-01],
       [9.34446221e-01, 6.55537788e-02],
       [9.63441046e-01, 3.65589544e-02],
       [9.61896070e-01, 3.81039298e-02],
       [9.99995575e-01, 4.42495838e-06],
       [1.13424758e-01, 8.86575242e-01],
       [9.66572762e-01, 3.34272380e-02],
       [9.33726105e-01, 6.62738946e-02],
       [2.52682050e-01, 7.47317950e-01],
       [4.37158545e-04, 9.99562841e-01],
       [1.60798638e-01, 8.39201362e-01],
       [3.54092048e-02, 9.64590795e-01],
       [8.97897615e-01, 1.02102385e-01],
       [3.20321550e-01, 6.79678450e-01],
       [9.64316165e-01, 3.56838350e-02],
       [1.59883579e-02, 9.84011642e-01],
       [3.23059044e-01, 6.76940956e-01],
       [7.89481343e-01, 2.10518657e-01],
       [9.63441046e-01, 3.65589544e-02],
       [2.72371755e-02, 9.72762824e-01],
       [4.06513408e-01, 5.93486592e-01],
       [3.33613768e-01, 6.66386232e-01]])

In [57]:
accuracy_score(y_test,y_pred_nb)

0.7789115646258503

In [58]:
confusion_matrix(y_test,y_pred_nb)

array([[145,  39],
       [ 26,  84]])

In [59]:
print(classification_report(y_test,y_pred_nb))

              precision    recall  f1-score   support

           0       0.85      0.79      0.82       184
           1       0.68      0.76      0.72       110

    accuracy                           0.78       294
   macro avg       0.77      0.78      0.77       294
weighted avg       0.79      0.78      0.78       294